# Default listener (Dùng cho nội bộ Server Docker)
listener 1883
protocol mqtt

# WebSocket listener (Dùng cho Raspberry Pi qua Cloudflare)
listener 9001
protocol websockets

# TẠM THỜI cho phép anonymous để test, sau khi chạy được bắt buộc phải tắt
allow_anonymous true

# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_timestamp true

# Tắt 'log_type all' đi và thay bằng các mức độ cơ bản này:
log_type error
log_type warning
log_type notice
log_type information

# Thêm dòng này nếu bạn muốn ẩn luôn thông báo Client (như Docker) kết nối/ngắt kết nối liên tục
# connection_messages false